spring.application.name=rag-knowledge-base
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

app.upload.chunk-size=500
app.upload.overlap=100
app.upload.max-file-size=10
app.embedding.dimension=8
app.document-chunk-repository.file-path=target/document-chunks.json
app.document-chunk-repository.repository-name=local-json-file
